language: scala
sudo: required
os:
- linux
#- osx
scala:
- 2.11.8
- 2.12.8
jdk:
- oraclejdk8
script: "./scripts/test.sh"
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot"
  - "$HOME/.m2"
before_install:
- |
  if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_aaa7ed714ca2_key -iv $encrypted_aaa7ed714ca2_iv -in secrets.tar.enc -out secrets.tar -d
    tar xvf secrets.tar
    chmod 777 scripts/publish.sh
  fi
jobs:
  include:
    - stage: release
      script: chmod 777 scripts/release.sh && ./scripts/release.sh
      scala: 2.12.8
      os: linux
    - stage: deploy_2.11
      script: ./scripts/publish.sh
      name: "Deploying scala 2.11.8 artifacts"
      scala: 2.11.8
      os: linux
    - stage: deploy_2.12
      script: ./scripts/publish.sh
      name: "Deploying scala 2.12.8 artifacts"
      scala: 2.12.8
      os: linux
stages:
  - name: test
  - name: release
    if: branch = master AND type != pull_request
  - name: deploy_2.11
    if: branch = master AND type != pull_request
  - name: deploy_2.12
    if: branch = master AND type != pull_request
