version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                wget -q https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb
                sudo dpkg -i sbt-1.1.0.deb
  test:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test version 2.11.11
            command: "sbt ++2.11.11 clean compile test:compile test"
        - run:
            name: Test version 2.12.4
            command: "sbt ++2.12.4 clean compile test:compile test"
#  test_specs2:
#      docker:
#        - image: circleci/openjdk:8-jdk
#      steps:
#        - checkout
#        - run:
#            name: Test version 2.11.11
#            command: "sbt ++2.11.11 \"project specs2\" clean compile test:compile test"
#        - run:
#            name: Test version 2.12.4
#            command: "sbt ++2.12.4 \"project specs2\" clean compile test:compile test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          required:
            - build
#      - test_scalatest:
#          requires:
#            - build
#      - test_specs2:
#          requires:
#            - build