version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                wget -q https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb
                sudo dpkg -i sbt-1.1.0.deb
  scalatest_2.12.4:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt ++2.12.4 \"project scalaTest\" compile test:compile test"
  scalatest_2.11.11:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt ++2.11.11 \"project scalaTest\" compile test:compile test"
  specs2_2.12.4:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt ++2.12.4 \"project specs2\" compile test:compile test"
  specs2_2.11.11:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - checkout
        - run:
            name: Test
            command: "sbt ++2.11.11 \"project specs2\" compile test:compile test"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - scalatest_2.12.4:
          requires:
            - build
      - scalatest_2.11.11:
          requires:
            - build
      - specs2_2.12.4:
          requires:
            - build
      - specs2_2.11.11:
          requires:
            - build