version: 2
jobs:
  build:
       docker:
         - image: circleci/openjdk:8-jdk
       steps:
         - checkout
         - run:
             name: Insatll sbt
             command: |
                wget -q https://dl.bintray.com/sbt/debian/sbt-1.1.0.deb
                sudo dpkg -i sbt-1.1.0.deb
  test_scalatest:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - run:
            name: Test
            command: "sbt \"project scalaTest\" \"+ compile\" \"+ test:compile\" \"+ test\""
  test_specs2:
      docker:
        - image: circleci/openjdk:8-jdk
      steps:
        - run:
            name: Test
            command: "sbt \"project specs2\" \"+ compile\" \"+ test:compile\" \"+ test\""
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_scalatest:
          requires:
            - build
      - test_specs2:
          requires:
            - build